[thumbnailing]
max-requests = 10
spacing-hint = 2
cache-size = 250

[clip-library]
close-import-dialog-after-import = True
last-clip-view = 2
last-folder = /home/louis/Downloads/appu

[export]
element-settings-dialog-height = 460
element-settings-dialog-width = 620
last-export-folder = /home/louis

[user-interface]
videoclip-background = 160
show-thumbnails = True
clip-font-name = Sans 9
prefs-dialog-height = 400
clip-font-color = 4294967210
selected-color = 119
edge-snap-deadband = 5
audioclip-background = 1318717120
show-waveforms = True
prefs-dialog-width = 600

[main-window]
show-timeline-toolbar = True
hpane-position = 879
last-folder = /home/louis/Downloads/appu
vpane-position = 450
height = 782
width = 1278
show-main-toolbar = True
full-screen = False

