#DavMail settings
#Thu Apr 15 10:05:41 CEST 2010
davmail.allowRemote=false
davmail.bindAddress=
#davmail.caldavAlarmSound=
davmail.caldavPastDelay=90
davmail.caldavPort=1080
davmail.defaultDomain=
davmail.disableUpdateCheck=false
davmail.enableProxy=false
davmail.forceActiveSyncUpdate=false
davmail.imapPort=
davmail.keepDelay=30
davmail.ldapPort=
davmail.logFilePath=/tmp/davmail.log
davmail.popPort=
davmail.proxyHost=s-proxy
davmail.proxyPassword=
davmail.proxyPort=3128
davmail.proxyUser=
davmail.sentKeepDelay=90
davmail.server=false
davmail.server.certificate.hash=6B\:53\:10\:0\:E7\:EC\:19\:F\:41\:67\:6\:36\:4C\:F7\:49\:F9\:1\:30\:56\:AF
davmail.showStartupBanner=false
davmail.smtpPort=
davmail.ssl.clientKeystoreFile=
davmail.ssl.clientKeystorePass=
davmail.ssl.clientKeystoreType=PKCS11
davmail.ssl.keyPass=
davmail.ssl.keystoreFile=
davmail.ssl.keystorePass=
davmail.ssl.keystoreType=JKS
davmail.ssl.pkcs11Config=
davmail.ssl.pkcs11Library=
davmail.url=https\://owa.rd.francetelecom.fr/exchange/
davmail.useSystemProxies=false
log4j.logger.davmail=DEBUG
log4j.logger.httpclient.wire=WARN
log4j.logger.org.apache.commons.httpclient=WARN
log4j.rootLogger=WARN
