#!/bin/sh

# performance boost
#if [ "$PS1" ] ; then  
#   mkdir -p -m 0700 /dev/cgroup/cpu/user/$$ > /dev/null 2>&1
#   echo $$ > /dev/cgroup/cpu/user/$$/tasks
#   echo "1" > /dev/cgroup/cpu/user/$$/notify_on_release
#fi

# load FTRD config
if [ -f ${MY_CONFIG_DIR}/ftrd_config ]; then
    . ${MY_CONFIG_DIR}/ftrd_config
fi

die() {
    result=$1
    shift
    echo ": $*" >&2
    exit $result
}

[ -d $MY_CONFIG_DIR ] || die 1 "must have variable MY_CONFIG_DIR set"

# for hsgtd
export TODO=$MY_CONFIG_DIR


export KEY_CMD="xkbcomp -w 0 -R/usr/share/X11/xkb/ ${MY_CONFIG_DIR}/keymap \"$DISPLAY\" "

export PATH=$PATH:/sbin:/usr/sbin:${MY_CONFIG_DIR}/bin:${MY_CONFIG_DIR}/cabal/bin
export PYTHONPATH=~/workspace/spydump/:~/workspace/spydump/tools
export PATH=$PATH:$PYTHONPATH/

# scripts from "Shell Scripting Recipes": http://shell.cfajohnson.com/ssr/ssr-scripts.tar.gz
SCRIPT_RECIPES=$HOME/.scripts_recipes/bin
[ -d $SCRIPT_RECIPES ] && export PATH=$PATH:$SCRIPT_RECIPES

# quicksnips: http://quicksnips.org/
QUICKSNIPS=$MY_CONFIG_DIR/quicksnips/bin
[ -d $QUICKSNIPS ] && export PATH=$PATH:$QUICKSNIPS


#export VIMRUNTIME=${MY_CONFIG_DIR}/vim
export XDG_CONFIG_HOME=${MY_CONFIG_DIR}


export LS_OPTIONS='--color=auto'
eval `dircolors $MY_CONFIG_DIR/dircolors`
alias ls='/bin/ls --group-directories-first $LS_OPTIONS'
alias l1='/bin/ls $LS_OPTIONS -1'
alias lb='/bin/ls $LS_OPTIONS -shapC'
alias ll='/bin/ls $LS_OPTIONS -l'
alias la='/bin/ls $LS_OPTIONS -Alh'
alias lsd='/bin/ls $LS_OPTIONS -d */'

alias grep='/bin/grep --color=auto'
alias fgrep='/bin/fgrep --color=auto'
alias egrep='/bin/egrep --color=auto'

# some more ls aliases
alias l='/bin/ls $LS_OPTIONS -CF'
alias lh='/bin/ls $LS_OPTIONS -lh'

export LESS="-R"
export EDITOR=vi

alias xpdf='/usr/bin/xpdf -z page'

#compose key activated in gtk apps
GTK_IM_MODULE=xim
export GTK_IM_MODULE

# burn cd: first ripit
alias burnit='flac -d *.flac && cdrdao write cd.toc && rm *.wav && eject'

alias twi='${MY_CONFIG_DIR}/bin/twitter -t -d -f ansi'

# google code update
alias upload_download='googlecode_upload.py -s "source distribution" -p pytomo -u louis.plissonneau -w Ab5PG7aC9MB9 -l "Featured,Type-Source,OpSys-All" '

# super man
function superman() { 
    /usr/bin/man "$@" || w3m -dump http://google.com/search\?q="$@"\&btnI | less 
}

# Créer un répertoire et l'ouvrir :
function mcd() { 
    mkdir "$@"
    cd "$@" 
}
#alias mcd='mkdir \!*; cd \!*'

# recupere la sortie std sur le buffer x
function x() {
    eval "$@" | tee >(xclip)
}

alias light-m='sudo $MY_CONFIG_DIR/bin/adjust_light.sh'
alias light-min='sudo $MY_CONFIG_DIR/bin/adjust_light.sh 0'
alias light-max='sudo $MY_CONFIG_DIR/bin/adjust_light.sh 100'

alias gvi='gvim'

#alias chrome='all_proxy=$chrome_proxy /usr/bin/google-chrome'

#restart_adb_server() {
#    ~/android/android-sdk-linux_86/tools/adb kill-server
#    ~/android/android-sdk-linux_86/tools/adb start-server
#}
#export -f restart_adb_server
export ANDROID_SDK=~/android/android-sdk-linux_x86
export ANDROID_NDK_ROOT=~/android/android-ndk-r5b
export ANDROID_NDK=$ANDROID_NDK_ROOT
#export ANDROID_NDK_TOOLCHAIN_ROOT=~/android-toolchain
export PATH=$PATH:$ANDROID_SDK/tools:$ANDROID_SDK/platform-tools
alias fix_adb='$ANDROID_SDK/platform-tools/adb kill-server;sudo $ANDROID_SDK/platform-tools/adb start-server'
alias tethering='sudo dhclient usb0'

#no more needed
#bad but needed to let default config of aptitude and still use python 2.6
#alias python='/usr/bin/python2.6'
#alias ipython='/usr/bin/python2.6 /usr/bin/ipython'
alias pyprofile='python -m cProfile -s time'

alias 'cd..'='cd ..'
alias pysh='ipython -p pysh'
alias pyl='pylint --output-format=colorized --reports=n --disable=C0103 --disable=W0141 --disable=E1101'

#alias print 'lpr \!* -Pps5'

alias saptu='sudo aptitude update'
alias saptdu='sudo aptitude dist-upgrade'
alias saptsu='sudo aptitude safe-upgrade'
alias aptg='aptitude search'
alias apts='aptitude show'
alias aptw='aptitude why'

alias hibernate='sudo /usr/sbin/pm-hibernate'
alias suspend='sudo /usr/sbin/pm-suspend'
alias suspend-hybrid='sudo /usr/sbin/pm-suspend-hybrid'

alias fixwifi='sudo iwconfig wlan0 txpower on'
alias presentation='impressive -t PageTurn'

alias images='feh -F -Z'
alias photos='pho -p'

EXTERNAL_OUTPUT="VGA1"
INTERNAL_OUTPUT="LVDS1"
alias ext-screen-off='xrandr --output $EXTERNAL_OUTPUT --off'
alias ext-screen='xrandr --auto --output $EXTERNAL_OUTPUT --auto --same-as $INTERNAL_OUTPUT'

alias cdc='cd $MY_CONFIG_DIR'

# keep trace of installed packages (even tentatives)
sapti() {
    if sudo aptitude install $@
	then
		# warning: will also store uninstalled packages
        	echo $@ >> ${MY_CONFIG_DIR}/aptitude_list_local
	fi
 }

saptr() {
    if sudo aptitude remove $@
	then
        	for package in $*
        	do
                	sed -i "/^[^#]/s/\(\<$package\>\)[[:space:]]*/# &\n/g" ${MY_CONFIG_DIR}/aptitude_list_local
        	done
        	sed -i '/^$/d' ${MY_CONFIG_DIR}/aptitude_list_local
	fi
 }



alias lst='tar tzf'
alias untar='tar xzvf'
alias j='jobs -l'
alias h='history|more'
 
alias less='less --quiet'
alias df='df --human-readable'
alias du='du --human-readable'
alias less='less -e -i -m -R'

# Pile de Répertoires
alias p='popd'

alias vlcn='vlc -I ncurses'

# git log
alias gl='git log --graph --pretty=format:"%Cred%h%Creset — %s %Cgreen(%cr)%Creset" --abbrev-commit --date=relative'
alias git_svn_sync_clean='git svn fetch; git merge remotes/clean'
alias gitst='git status'
alias gst='git status'
alias gco='git commit -a'

alias ps_mem='sudo /home/louis/config/bin/ps_mem.py'

#fresh() {
#    old_proxy=$http_proxy
#    unset http_proxy
#    sudo freshclam
#    export http_proxy=$old_proxy
#}
alias fresh='http_proxy="" sudo freshclam'

alias findusb='diff <(lsusb) <(sleep 3s && lsusb)'

# java
export JAVA_HOME=/usr/lib/jvm/java-6-openjdk
export PATH=$PATH:$JAVA_HOME/bin
#export PLUGIN_HOME=$JAVA_HOME
export PATH=$PATH:/opt/eclipse

export GNOME_DESKTOP_SESSION_ID=1
