#!/bin/sh

# Load resources
  
#xrdb -merge .Xresources
   
# Set up an icon tray
    
trayer --edge top --align right --SetDockType true --SetPartialStrut true \
    --expand true --width 10 --transparent true --height 8 --tint 0x191970 & #
      
# Set the background color
xsetroot -solid midnightblue
        
# wallpaper
xpmroot $MY_CONFIG_DIR/xmonad/desktop-background.png

# Fire up apps
         
# gajim &

wicd-client &

pidgin &

davmail &
          
xscreensaver -no-splash &

urxvtd -q -f -o &

xbattbar -c -t 2 -p 30 top &

# keymaps and key config
#setxkbmap fr -variant dvorak_prog
# warning: xkbmap resets xmodmap
#xmodmap $MY_CONFIG_DIR/xmodmaprc
# all is done with xkbcomp
cmd_key="xkbcomp -w 0 -R/usr/share/X11/xkb/ ${MY_CONFIG_DIR}/keymap \"$DISPLAY\" "
eval $cmd_key

# need to do it twice... I don't know why
eval $cmd_key
