[General]
version=4.5
versionFix=263424
windowSize=@Size(638 1006)
tools=TOOLBAR_TOP|TOOLBAR_BOTTOM|TOOL_ZOOMCOMBO|TOOL_ZOOMBUTTONS|TOOL_PAGECOMBO|TOOL_PREVNEXT|TOOL_FIRSTLAST|TOOL_BACKFORW|TOOL_OPEN|TOOL_FIND|TOOL_SELECT|TOOL_PRINT|TOOL_LAYOUT|TOOL_WHATSTHIS
gamma=2.2
resolution=100
cacheSize=10485760
pixelCacheSize=262144
lensSize=300
lensPower=3
browserProgram=
proxyUrl=
advancedFeatures=false
showTextLabel=false
modifiersForLens=Control+Shift
modifiersForSelect=Control
modifiersForLinks=Shift
thumbnailSize=64
thumbnailSmart=true
searchWordsOnly=true
searchCaseSensitive=false
searchRegExpMode=false
infoDialogTab=0
metaDialogTab=0
printerGamma=0
printerName=
printFile=
printCollate=false
printReverse=false
recentFiles=file:///home/louis/Downloads/books/ebooksclub.org__Network_algorithmics__an_interdisciplinary_approach_to_designing_fast_networked_devices.djvu, "file:///home/louis/Downloads/books/Mittelbach, Goossens. The LaTeX companion (2ed., AW, 2004)(KA)(T)(C)(ISBN 0201362996)(1119s)_ST_.djvu", file:///home/louis/Downloads/books/latex_companion_graphics.djvu, "file:///home/louis/Downloads/books/Norvig P. Paradigms of Artificial Intelligence Programming.. Case Studies in Common Lisp (Morgan Kaufmann, 1991)(ISBN 1558601910)(600dpi)(T)(973s)_CsAi_.djvu", file:///home/louis/Downloads/books/Ye N. (ed.) The handbook of data mining .djvu, "file:///home/louis/Downloads/books/Harrop J. OCaml for scientists (Flying Frog Consultancy, 2005)(T)(281s)_CsPl_.djvu"

[forEmbeddedPlugin]
remember=false
options=SHOW_SCROLLBARS|SHOW_FRAME|SHOW_MAPAREAS|HANDLE_MOUSE|HANDLE_KEYBOARD|HANDLE_LINKS|HANDLE_CONTEXTMENU
zoom=-1
state=@ByteArray()

[forFullPagePlugin]
remember=true
options=SHOW_TOOLBAR|SHOW_SCROLLBARS|SHOW_FRAME|SHOW_MAPAREAS|HANDLE_MOUSE|HANDLE_KEYBOARD|HANDLE_LINKS|HANDLE_CONTEXTMENU
zoom=-1
state=@ByteArray()

[forStandalone]
remember=true
options=SHOW_MENUBAR|SHOW_TOOLBAR|SHOW_STATUSBAR|SHOW_SCROLLBARS|SHOW_FRAME|SHOW_MAPAREAS|HANDLE_MOUSE|HANDLE_KEYBOARD|HANDLE_LINKS|HANDLE_CONTEXTMENU
zoom=-2
state=@ByteArray(\0\0\0\xff\0\0\0\0\xfd\0\0\0\x1\0\0\0\0\0\0\0\xe6\0\0\x2\xc4\xfc\x2\0\0\0\x1\xfc\0\0\0\x36\0\0\x2\xc4\0\0\0\0\0\xff\xff\xff\xfa\xff\xff\xff\xff\x2\0\0\0\x3\xfb\0\0\0\x1a\0t\0h\0u\0m\0\x62\0n\0\x61\0i\0l\0\x44\0o\0\x63\0k\0\0\0\0\0\xff\xff\xff\xff\0\0\0r\0\xff\xff\xff\xfb\0\0\0\x16\0o\0u\0t\0l\0i\0n\0\x65\0\x44\0o\0\x63\0k\0\0\0\0\0\xff\xff\xff\xff\0\0\0r\0\xff\xff\xff\xfb\0\0\0\x10\0\x66\0i\0n\0\x64\0\x44\0o\0\x63\0k\0\0\0\0\0\xff\xff\xff\xff\0\0\0\xcb\0\xff\xff\xff\0\0\x2~\0\0\x3\x95\0\0\0\x4\0\0\0\x4\0\0\0\b\0\0\0\b\xfc\0\0\0\x1\0\0\0\x2\0\0\0\x1\0\0\0\xe\0t\0o\0o\0l\0\x62\0\x61\0r\x1\0\0\0\0\xff\xff\xff\xff\0\0\0\0\0\0\0\0)

[forFullScreen]
remember=true
options=SHOW_FRAME|SHOW_MAPAREAS|HANDLE_MOUSE|HANDLE_KEYBOARD|HANDLE_LINKS|HANDLE_CONTEXTMENU
zoom=-1
state=@ByteArray()

[Printer-PS]
color=true
frame=false
cropMarks=false
psLevel=3
autoOrient=true
landscape=false
zoom=0
booklet=false
bookletSheets=0
bookletRectoVerso=0
bookletShift=0
bookletCenter=18
bookletCenterAdd=40
